# Generated by Django 5.0.3 on 2024-09-24 09:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheWire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thewirenews',
            old_name='new_content',
            new_name='news_content',
        ),
        migrations.AddField(
            model_name='thewirenews',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='static/images/news/'), upload_to='news/'),
        ),
    ]
