# Generated by Django 5.0.3 on 2024-09-25 00:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheWire', '0002_rename_new_content_thewirenews_news_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thewirenews',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='static/images/news/'), upload_to=''),
        ),
    ]
