# Generated by Django 5.0.3 on 2024-09-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheWire', '0003_alter_thewirenews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thewirenews',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/'),
        ),
    ]
