# Generated by Django 5.0.3 on 2024-10-16 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistickets',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_device', to='Ticketing.deviceinformation'),
        ),
    ]
