# Generated by Django 5.0.3 on 2024-10-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaverequest', '0002_leaverequest_leaverouting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverouting',
            name='status',
            field=models.CharField(default='Waiting for Approval', max_length=50),
        ),
    ]
