# Generated by Django 5.0.3 on 2024-10-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaverequest', '0003_alter_leaverouting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='days',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(default='On Process', max_length=10),
        ),
    ]
