# Generated by Django 5.0.3 on 2024-10-07 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaverequest', '0004_leaverequest_days_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverouting',
            name='remarks',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='leaverouting',
            name='leave_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='Leaverequest.leaverequest'),
        ),
    ]
