# Generated by Django 5.0.3 on 2024-10-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaverequest', '0005_leaverouting_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverouting',
            name='remarks',
            field=models.TextField(),
        ),
    ]
