# Generated by Django 5.0.3 on 2024-10-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaverequest', '0006_alter_leaverouting_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverouting',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
