# Generated by Django 5.0.3 on 2024-10-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_notification_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='page',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
