# Generated by Django 5.0.3 on 2024-12-06 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overtime', '0002_assignedline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_leaders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='Overtime.overtimegroup')),
            ],
            options={
                'unique_together': {('group', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='SupervisorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='overtimegroup',
            name='supervisor_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sup_group', to='Overtime.supervisorgroup'),
        ),
        migrations.DeleteModel(
            name='AssignedLine',
        ),
        migrations.AlterUniqueTogether(
            name='overtimegroup',
            unique_together={('supervisor_group', 'line_leader')},
        ),
    ]
