# Generated by Django 5.0.3 on 2024-09-30 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
        ('Settings', '0002_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='birth_place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='children',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='contact_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='contact_no',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='contact_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='contact_person',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='contact_relation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='father',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Settings.gender'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='mother',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='present_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='primary_school',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='provincial_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='secondary_school',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='spouse',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='tertiary_school',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='vocational_school',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='EmploymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
                ('date_hired', models.DateField()),
                ('tin_number', models.CharField(max_length=100, null=True)),
                ('sss_number', models.CharField(max_length=100, null=True)),
                ('hdmf_number', models.CharField(max_length=100, null=True)),
                ('philhealth', models.CharField(max_length=100, null=True)),
                ('bank_account', models.CharField(max_length=100, null=True)),
                ('Status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Settings.status')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_approver', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Settings.department')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Settings.lines')),
                ('name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employment_info', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Settings.position')),
            ],
        ),
    ]
