# Generated by Django 5.0.3 on 2024-10-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_personalinformation_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='contact_address',
            new_name='contact_baranggay',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='present_address',
            new_name='contact_city',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='provincial_address',
            new_name='contact_province',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='contact_street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='present_baranggay',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='present_city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='present_province',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='present_street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='provincial_baranggay',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='provincial_city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='provincial_province',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='provincial_street',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
