# Generated by Django 5.0.3 on 2024-10-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_rename_contact_address_personalinformation_contact_baranggay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='middlename',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
