# Generated by Django 5.0.3 on 2024-10-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_employmentinformation_line_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentinformation',
            name='line_leader',
        ),
    ]
