# Generated by Django 5.0.3 on 2024-10-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_remove_employmentinformation_line_leader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='contact_person',
            new_name='contact_firstname',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='contact_lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='contact_middlename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
