# Generated by Django 5.0.3 on 2024-10-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_rename_contact_person_personalinformation_contact_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='no_of_children',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
