# Generated by Django 5.0.3 on 2024-10-03 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_alter_employmentinformation_approver'),
        ('Settings', '0003_position_is_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentinformation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Settings.department'),
        ),
        migrations.AlterField(
            model_name='employmentinformation',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Settings.lines'),
        ),
    ]
