# Generated by Django 5.0.3 on 2024-10-15 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overtime', '0001_initial'),
        ('Profile', '0010_alter_employmentinformation_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentinformation',
            name='shuttle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Overtime.pickuppoint'),
        ),
    ]
