# Generated by Django 5.0.3 on 2024-09-27 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PRForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=50, null=True)),
                ('ctrl_no', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('purpose', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prform_requestor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
