# Generated by Django 5.0.3 on 2024-09-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prform',
            name='approved_by',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
    ]
