# Generated by Django 5.0.3 on 2024-09-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prform', '0002_prform_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prform',
            name='ctrl_no',
            field=models.CharField(default='N/A', max_length=50, null=True),
        ),
    ]
