# Generated by Django 5.0.3 on 2024-10-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prform', '0003_alter_prform_ctrl_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prform',
            name='approved_by',
            field=models.CharField(default='For Approval', max_length=100, null=True),
        ),
    ]
