# Generated by Django 5.0.3 on 2024-10-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prform', '0004_alter_prform_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prform',
            name='approved_by',
            field=models.CharField(default='-', max_length=100, null=True),
        ),
    ]
