# Generated by Django 5.0.3 on 2024-09-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_event_submitted_at_event_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
