# Generated by Django 5.0.3 on 2024-09-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0003_alter_event_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.TextField(null=True),
        ),
    ]
