# Generated by Django 5.0.3 on 2024-09-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0004_event_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, upload_to='calendars/'),
        ),
    ]
