# Generated by Django 5.0.3 on 2024-09-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0005_alter_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, upload_to='calendar/'),
        ),
    ]
