# Generated by Django 5.0.3 on 2024-10-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0006_alter_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
