# Generated by Django 5.0.3 on 2024-10-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_approver',
            field=models.BooleanField(default=False),
        ),
    ]
