# Generated by Django 5.0.3 on 2024-10-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0003_position_is_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='approver_level',
            field=models.IntegerField(default=1),
        ),
    ]
