# Generated by Django 5.0.3 on 2024-09-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timelogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetimelogs',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
