# Generated by Django 5.0.3 on 2024-09-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timelogs', '0003_alter_employeetimelogs_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetimelogs',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeetimelogs',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
