# Generated by Django 5.0.3 on 2024-10-03 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('template', models.ImageField(blank=True, upload_to='cert-template/')),
            ],
        ),
        migrations.CreateModel(
            name='CertSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('signature', models.ImageField(blank=True, upload_to='signatures/')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_date', models.DateField()),
                ('cert_name', models.CharField(max_length=100, null=True)),
                ('cert_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Certificate.certificate')),
                ('cert_speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Certificate.certspeaker')),
            ],
        ),
        migrations.CreateModel(
            name='Awardees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('awardeee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awardees', to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Certificate.certificatelist')),
            ],
        ),
    ]
