# Generated by Django 5.0.3 on 2024-10-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='certificatelist',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
