# Generated by Django 5.0.3 on 2024-10-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0002_certificate_created_at_certificatelist_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='certificatelist',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
