# Generated by Django 5.0.3 on 2024-10-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0003_alter_certificate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certspeaker',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
