# Generated by Django 5.0.3 on 2024-10-04 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate', '0004_certificate_certificate_type_certspeaker_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Certificate.certspeaker')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Certificate.certificate')),
            ],
        ),
    ]
