# Generated by Django 5.0.3 on 2024-09-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelogin',
            name='is_accounting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeelogin',
            name='is_clinic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeelogin',
            name='is_iad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeelogin',
            name='is_the_wire',
            field=models.BooleanField(default=False),
        ),
    ]
