# Generated by Django 5.0.3 on 2024-09-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0002_employeelogin_is_accounting_employeelogin_is_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelogin',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
    ]
