# Generated by Django 5.0.3 on 2024-09-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0004_employeelogin_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogin',
            name='idnumber',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
