# Generated by Django 5.0.3 on 2024-09-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0006_alter_employeelogin_idnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeelogin',
            name='idnumber',
        ),
    ]
