# Generated by Django 5.0.3 on 2024-09-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0007_remove_employeelogin_idnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelogin',
            name='idnumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
