# Generated by Django 5.0.3 on 2024-09-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0008_employeelogin_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
