# Generated by Django 5.0.3 on 2024-10-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0009_alter_employeelogin_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelogin',
            name='is_approver',
            field=models.BooleanField(default=False),
        ),
    ]
