# Generated by Django 5.0.3 on 2024-10-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0010_employeelogin_is_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogin',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='profile/'),
        ),
    ]
