# Generated by Django 5.0.3 on 2024-10-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0011_alter_employeelogin_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelogin',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
