# Generated by Django 5.0.3 on 2024-10-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0013_employeelogin_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
