# Generated by Django 5.0.3 on 2024-10-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0014_alter_employeelogin_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogin',
            name='is_approved',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
