# Generated by Django 5.0.3 on 2024-10-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0015_alter_employeelogin_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelogin',
            name='is_approved',
            field=models.CharField(default='For Approval', max_length=20),
        ),
    ]
