# Generated by Django 5.0.3 on 2024-10-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0017_alter_employeelogin_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelogin',
            name='is_hrmanager',
            field=models.BooleanField(default=False),
        ),
    ]
