# Generated by Django 5.0.3 on 2024-10-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0018_employeelogin_is_hrmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelogin',
            name='is_ot_coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
