# Generated by Django 5.0.3 on 2024-10-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0019_employeelogin_is_ot_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelogin',
            name='is_mis',
            field=models.BooleanField(default=False),
        ),
    ]
