# Generated by Django 5.0.3 on 2024-10-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0020_employeelogin_is_mis'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelogin',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
