# Generated by Django 5.0.3 on 2024-09-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_userresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarter',
            name='status',
        ),
        migrations.AlterField(
            model_name='quarter',
            name='state',
            field=models.CharField(default='OPEN', max_length=7, null=True),
        ),
    ]
