# Generated by Django 5.0.3 on 2024-09-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0003_remove_quarter_status_alter_quarter_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
