# Generated by Django 5.0.3 on 2024-09-29 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0004_userresponse_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyform',
            name='quarter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Survey.quarter'),
        ),
    ]
