# Generated by Django 5.0.3 on 2024-09-29 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0005_surveyform_quarter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyform',
            name='quarter',
        ),
        migrations.AddField(
            model_name='surveyform',
            name='survey_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Survey.userresponse'),
        ),
    ]
