# Generated by Django 5.0.3 on 2025-01-06 04:59

import Accounting.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField()),
                ('loan_amount', models.CharField(max_length=100, null=True)),
                ('payment', models.CharField(max_length=50, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.financetype')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField()),
                ('amount', models.CharField(max_length=20, null=True)),
                ('claimed_amount', models.CharField(max_length=20, null=True)),
                ('balance', models.CharField(max_length=20, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.financetype')),
            ],
        ),
        migrations.CreateModel(
            name='PerfectAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField()),
                ('amount', models.CharField(max_length=20, null=True)),
                ('is_credited', models.BooleanField(default=False)),
                ('date_credited', models.DateField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.financetype')),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField()),
                ('desired_savings', models.CharField(max_length=100, null=True)),
                ('savings', models.CharField(max_length=50, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('savings_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounting.financetype')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_start', models.DateField(null=True)),
                ('payroll_end', models.DateField(null=True)),
                ('payslip', models.FileField(upload_to=Accounting.models.payslip_upload_path, validators=[Accounting.models.validate_file_size])),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('received_date', models.DateTimeField(null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employee', 'payroll_start', 'payroll_end')},
            },
        ),
    ]
