# Generated by Django 5.0.3 on 2024-09-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
