# Generated by Django 5.0.3 on 2024-09-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0002_training_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='state',
            new_name='is_closed',
        ),
    ]
