# Generated by Django 5.0.3 on 2024-09-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0003_rename_state_training_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantresponse',
            name='is_evaluater',
            field=models.BooleanField(default=False),
        ),
    ]
