# Generated by Django 5.0.3 on 2024-09-30 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0004_participantresponse_is_evaluater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantresponse',
            old_name='is_evaluater',
            new_name='is_evaluated',
        ),
    ]
