# Generated by Django 5.0.3 on 2024-10-01 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0006_trainingform'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingform',
            name='assessment',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='trainingform',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingform',
            name='result_impact',
            field=models.TextField(blank=True),
        ),
    ]
