# Generated by Django 5.0.3 on 2024-10-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0007_trainingform_assessment_trainingform_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
