# Generated by Django 5.0.3 on 2024-10-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0008_trainingform_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingform',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
