# Generated by Django 5.0.3 on 2024-10-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0010_trainingapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantresponse',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
