# Generated by Django 5.0.3 on 2024-10-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0011_participantresponse_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantresponse',
            name='is_approved',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
